baseURL = "https://mugiwara2.netlify.com/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Blog de Mugi"
theme = "Hugo-One"
themesDir = "../../"   #Don't use this, only for netlify

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "mugiwara2"

enableRobotsTXT = true
enableGitInfo = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Mugi"
	description = "Baks"
	avatar = "/img/AvatarMug.jpg"
	motto = "Je vais poster sur ce site ma nouvelle : Baks"
	enableToc = true
	enableShareCard = true

	favicon = "/img/AvatarFav.png"
  	
  	#Background settings 
	enableColorBG = false
	bgBlur = "0px"
	bgImage = "/img/bg1.jpeg "
  
	#Post-displaying Settings
	enableTags = false
	enableCategories = true

	#Cards or posts shown per page
	itemsPerPage = 8

	#Set whether you're hosting "cards" or "post"
	contentType = "post"

	#Enable Twitter Emoji
	twitterEmoji=true

	copyright = ["BY-NC-ND", "This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License."]

	siteStartYear = 2018

	youtubeName = "Nicolas Tvn"

	iconAbout = "user secret"
	iconAboutReturn = "step backward"

[social]
	email = "nico.thouvenin13@gmail.com"
	github = "Nico-Mugi"
	linkedin = "nicolas-thouvenin-2844ba150"
	facebook = "NicolasTvnn"
	youtube = "UCf-IQVrTZ5X2iQOZooDXO7Q"