baseURL = "https://mugiwara2.netlify.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Blog de Mugi"
theme = "Hugo-One"
themesDir = "../../"   #Don't use this, only for netlify

RemovePathAccents = false

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

disqusShortname = "dream-plus"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	author = "Mugi"
	description = "Mugi : I'm just trying some stuff for myself (and my GF aswell)."
	avatar = "/img/AvatarFav.png"
	motto = "Je vais postééé sur ce site ma nouvelle : Baks"
	enableToc = true
	enableShareCard = true

	favicon = "/img/AvatarFav.png"
  	
  	#Background settings 
	enableColorBG = false
	bgBlur = "0px"
	bgImage = "/img/bg1.jpeg "
  
	#Post-displaying Settings
	enableTags = true
	enableCategories = true

	#Cards or posts shown per page
	itemsPerPage = 4

	#Set whether you're hosting "cards" or "post"
	contentType = "post"

	#Enable Twitter Emoji
	twitterEmoji=true

[social]
	email = "nico.thouvenin13@gmail.com"
	github = "Nico-Mugi"
	facebook = "nicolas.thouvenin.108"
	linkedin = "nicolas-thouvenin-2844ba150"
	siteStartYear = 2018